set_property PACKAGE_PIN W5 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]

set_property PACKAGE_PIN T18 [get_ports reset_i]
set_property IOSTANDARD LVCMOS33 [get_ports reset_i]

set_property PACKAGE_PIN U18 [get_ports startOperation_i]
set_property IOSTANDARD LVCMOS33 [get_ports startOperation_i]

set_property PACKAGE_PIN T17 [get_ports btnr_i]
set_property IOSTANDARD LVCMOS33 [get_ports btnr_i]

set_property PACKAGE_PIN W19 [get_ports btnl_i]
set_property IOSTANDARD LVCMOS33 [get_ports btnl_i]

set_property PACKAGE_PIN U16 [get_ports done_o]
set_property IOSTANDARD LVCMOS33 [get_ports done_o]

# x_i[7:0]
set_property PACKAGE_PIN V17 [get_ports {x_i[0]}]
set_property PACKAGE_PIN V16 [get_ports {x_i[1]}]
set_property PACKAGE_PIN W16 [get_ports {x_i[2]}]
set_property PACKAGE_PIN W17 [get_ports {x_i[3]}]
set_property PACKAGE_PIN W15 [get_ports {x_i[4]}]
set_property PACKAGE_PIN V15 [get_ports {x_i[5]}]
set_property PACKAGE_PIN W14 [get_ports {x_i[6]}]
set_property PACKAGE_PIN W13 [get_ports {x_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports x_i[*]]

# y_i[7:0]
set_property PACKAGE_PIN V2 [get_ports {y_i[0]}]
set_property PACKAGE_PIN T3 [get_ports {y_i[1]}]
set_property PACKAGE_PIN T2 [get_ports {y_i[2]}]
set_property PACKAGE_PIN R3 [get_ports {y_i[3]}]
set_property PACKAGE_PIN W2 [get_ports {y_i[4]}]
set_property PACKAGE_PIN U1 [get_ports {y_i[5]}]
set_property PACKAGE_PIN T1 [get_ports {y_i[6]}]
set_property PACKAGE_PIN R2 [get_ports {y_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports y_i[*]]

# finanode_o[3:0]
set_property PACKAGE_PIN W4 [get_ports {finanode_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {finanode_o[3]}]
set_property PACKAGE_PIN V4 [get_ports {finanode_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {finanode_o[2]}]
set_property PACKAGE_PIN U4 [get_ports {finanode_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {finanode_o[1]}]
set_property PACKAGE_PIN U2 [get_ports {finanode_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {finanode_o[0]}]

# LED_out_o[6:0]
set_property PACKAGE_PIN W7 [get_ports {LED_out_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_out_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_out_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_out_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_out_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_out_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_out_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[0]}]
